# Generated by Django 4.0.4 on 2022-05-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='_id',
            new_name='id',
        ),
    ]
