# Generated by Django 4.0.4 on 2022-05-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='portalCode',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phoneNumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=30000, max_digits=7, null=True),
        ),
    ]
