# Generated by Django 4.0.4 on 2022-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_shippingaddress_portalcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, default='Việt Nam', max_length=200, null=True),
        ),
    ]
