# Generated by Django 4.0.4 on 2022-05-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
