# Generated by Django 4.0.4 on 2022-05-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_order_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
