# Generated by Django 4.0.4 on 2022-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_confirmedat_order_isconfirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
